### ISSUE TITLE
Broken links on the official `schema.data.gouv.fr` website

### ISSUE THREAD

**Issue by holyhope** [CEREMA/schema-aire-livraison#1]
Hello,

I landed on this repository from <https://schema.data.gouv.fr/CEREMA/schema-aire-livraison/0.1.0/>.
It seems that all links on that web pages are broken.
I am not sure that is the right place for the issue, but I am sure you could transfer the issue to the appropriate team.

I suggest to either publish all assets to `schema.data.gouv.fr` website so it will be accessible with relative URLs, or make all links in this repository absolute URLs pointing to github assets.

Thank you

**Comment by datagistips** [comment]
Hi, effectively, there is a problem. 0.1.0 is an old tag, which is a bit strange (for instance, in https://schema.data.gouv.fr/CEREMA/schema-aire-livraison/0.1.0/1-Creer-Documentation.bat). I've just uploaded my local repo with tag v0.1.0. Let's see tomorrow how it is going. Automatic processes are launched by data.gouv.fr to make github repo content accessible from schema.data.gouv.fr, which I can't modify. If the problem remains, I'll contact data.gouv.fr

**Comment by holyhope** [comment]
I see no difference.
I am pretty sure you should reach them out, the website looks a bit inconsistent to me: The page returns a `200` HTTP status, but a Not found body.

If you want I could contact them by myself, but I do not know how... 😢 

```
curl -vs https://schema.data.gouv.fr/CEREMA/schema-aire-livraison/0.1.0/1-Creer-Documentation.bat -o /dev/null 
* Host schema.data.gouv.fr:443 was resolved.
* IPv6: (none)
* IPv4: 37.59.183.91
*   Trying 37.59.183.91:443...
* Connected to schema.data.gouv.fr (37.59.183.91) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [10 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [6683 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.data.gouv.fr
*  start date: Jan 22 22:09:39 2024 GMT
*  expire date: Apr 21 22:09:38 2024 GMT
*  subjectAltName: host "schema.data.gouv.fr" matched cert's "*.data.gouv.fr"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
} [5 bytes data]
> GET /CEREMA/schema-aire-livraison/0.1.0/1-Creer-Documentation.bat HTTP/1.1
> Host: schema.data.gouv.fr
> User-Agent: curl/8.6.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/1.1 200 OK
< server: nginx/1.25.4
< date: Thu, 07 Mar 2024 14:53:38 GMT
< content-type: text/html
< content-length: 77871
< last-modified: Thu, 29 Feb 2024 09:18:00 GMT
< etag: "65e04bc8-1302f"
< cache-control: public
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: Origin,Authorization,Accept,DNT,User-Agent,If-Modified-Since,Cache-Control,Content-Type,Range
< access-control-allow-credentials: true
< accept-ranges: bytes
```

**Comment by datagistips** [comment]
Thanks

Don't worry, I'm going to contact them

Issues can be made [here](https://github.com/etalab/schema.data.gouv.fr/issues)

**Comment by Pierlou** [comment]
Hello, schema.data.gouv here :wave:
These issues come from the fact that links [in the README.md](https://github.com/CEREMA/schema-aire-livraison/blob/a34507752cbe5a56a098eb2be9954e5c34aba290/README.md?plain=1#L29) are relative, so they depend on the website they are displayed on, which is why they work fine on github (as the files are there) but not on schema.data.gouv.
A quick fix would be to refence the whole URLs, for instance:
`[Voir le schéma version **ultra** au format TableSchema (json)](documentation/schema-page-ultra.md)`
becomes
`[Voir le schéma version **ultra** au format TableSchema (json)](https://github.com/CEREMA/schema-aire-livraison/blob/main/schema.json)`

**Comment by datagistips** [comment]
Ok, it's done

https://github.com/CEREMA/schema-aire-livraison/commit/b525613a1e431832c6866d9fc308a9679cfa6ae1

**Comment by holyhope** [comment]
Thank you for taking care of that!.
I think that you will need to push a new tag in order to publish the changes..?

**Comment by datagistips** [comment]
Thank you
Yes, or I will replace the previous one

**Comment by holyhope** [comment]
It worked. Thank you again for your help.
